In [ ]:
import numpy as np

array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [ ]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [1]:
list_a = [1,2,3]
list_a +[2]


[1, 2, 3, 2]

In [2]:
list_a = [1,2,3]
list_a +[2,4]

[1, 2, 3, 2, 4]

In [6]:
import numpy as np
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [8]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array_b[1]

array([4, 5, 6])

In [10]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [11]:
array_b - array_a


array([[-6, -6, -6],
       [-3, -3, -3]])

In [40]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[2,3,3],[9,5,2]])

In [41]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [42]:
b

array([[2, 3, 3],
       [9, 5, 2]])

In [43]:
a * b

array([[ 2,  6,  9],
       [27, 20, 10]])

In [44]:
a.shape

(2, 3)

In [45]:
b.shape

(2, 3)

In [46]:
a/b

array([[0.5       , 0.66666667, 1.        ],
       [0.33333333, 0.8       , 2.5       ]])

In [47]:
a + b

array([[ 3,  5,  6],
       [12,  9,  7]])

In [25]:
np.add(a,b)

array([[ 4,  6,  6],
       [18, 10,  4]])

In [26]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.multiply(a,b)

array([[ 4,  9,  9],
       [81, 25,  4]])

In [29]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
a.shape,b.shape


((2, 3), (2, 3))

In [37]:
b=b.reshape(3,2)
b

array([[2, 3],
       [3, 9],
       [5, 2]])

In [38]:
np.matmul(a,b)

array([[28, 39],
       [43, 76]])