In [ ]:
import numpy as np

array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [ ]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
list_a = [1,2,3]
list_a + [2,4]
## Since lists don't work elementwise, we're concatenating [2] to list_a.

[1, 2, 3, 2, 4]

In [ ]:
list_a.extend([2,4])

In [ ]:
list_a

[1, 2, 3, 2, 4]

In [ ]:
array_a + 2
## Element Wise addition adds 2 to each element of array_a.

array([ 9, 10, 11])

In [ ]:
array_a

array([7, 8, 9])

In [ ]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_b[1]

array([4, 5, 6])

In [ ]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [ ]:
array_b - array_a

array([[-6, -6, -6],
       [-3, -3, -3]])

In [ ]:
a = np.array([[1,2,3],[3,5,2]])
b = np.array([[2,3,3],[9,5,2]])

In [ ]:
a

array([[1, 2, 3],
       [3, 5, 2]])

In [ ]:
b

array([[2, 3, 3],
       [9, 5, 2]])

In [ ]:
a * b

array([[ 2,  6,  9],
       [27, 25,  4]])

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(2, 3)

In [ ]:
a/b

array([[0.5       , 0.66666667, 1.        ],
       [0.33333333, 1.        , 1.        ]])

In [ ]:
a + b

array([[ 3,  5,  6],
       [12, 10,  4]])

In [ ]:
np.add(a,b)

array([[ 5,  8,  9],
       [21, 15,  6]])

In [ ]:
np.subtract(a,b)

array([[-1, -1,  0],
       [-6,  0,  0]])

In [ ]:
np.multiply(a,b)

array([[ 2,  6,  9],
       [27, 25,  4]])

In [ ]:
np.matmul(a,b) #cant work same shape

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
a = np.array([[1,2,3],[3,5,2]])
b = np.array([[2,3,3,4],[9,5,2,6],[9,5,2,6]])

In [ ]:
a

array([[1, 2, 3],
       [3, 5, 2]])

In [ ]:
b

array([[2, 3, 3, 4],
       [9, 5, 2, 6],
       [9, 5, 2, 6]])

In [ ]:
a.shape,b.shape

((2, 3), (3, 4))

In [ ]:
np.matmul(a,b) #cross product

array([[47, 28, 13, 34],
       [69, 44, 23, 54]])

In [ ]:
import numpy as np
array_1D = np.array([10,11,12,13, 14])
array_1D
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [ ]:
import numpy as np
array_1D = np.array([10,11,12,13, 14])
print(array_1D * 2)
print('**********************')
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
print(array_2D * 2)
print('**********************')
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
print(array_3D * 2)

[20 22 24 26 28]
**********************
[[ 40  60  80 100 120]
 [ 86 108 130 152 174]
 [ 22  44  66  88 110]]
**********************
[[[  2   4   6   8  10]
  [ 22  42  62  82 102]]

 [[ 22  24  26  28  30]
  [102 104 106 108  10]]]


In [ ]:
#type conversion

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float64)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
6/2 #gives in float

3.0

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [ ]:
array_a = np.array([[1,2,0],[4,5,6]], dtype = bool)
array_a

array([[ True,  True, False],
       [ True,  True,  True]])

In [ ]:
array_a = np.array([[10,2,3],[4,5,6]], dtype = str)
array_a

array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')

In [ ]:
array_a = array_a.astype(int)

array([[10,  2,  3],
       [ 4,  5,  6]])

In [ ]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B



array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [ ]:
matrix_B[:,0:5:2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [ ]:
array_empty = np.empty((1000,30))
array_empty

array([[ 6.61776935e-310,  6.61776935e-310,  4.80595620e-310, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       ...,
       [ 3.39381442e-212,  6.61772244e-310,  6.61772274e-310, ...,
        -2.50350317e+279,  6.61772242e-310,  6.61772244e-310],
       [-2.29850456e+058,  6.61772242e-310,  6.61772244e-310, ...,
        -1.19478098e+074,  6.61772242e-310,  6.61772244e-310],
       [-6.59088117e+020,  6.61772244e-310,  6.61772244e-310, ...,
         3.21282118e-018,  6.61771322e-310,  6.61771322e-310]])

In [ ]:
array_empty[0,0] = 2.5

In [ ]:
array_empty

array([[ 2.50000000e+000,  6.61776935e-310,  4.80595620e-310, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       ...,
       [ 3.39381442e-212,  6.61772244e-310,  6.61772274e-310, ...,
        -2.50350317e+279,  6.61772242e-310,  6.61772244e-310],
       [-2.29850456e+058,  6.61772242e-310,  6.61772244e-310, ...,
        -1.19478098e+074,  6.61772242e-310,  6.61772244e-310],
       [-6.59088117e+020,  6.61772244e-310,  6.61772244e-310, ...,
         3.21282118e-018,  6.61771322e-310,  6.61771322e-310]])

In [ ]:
# zeros
array_0s = np.zeros((2,3))
array_0s


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array_0s = np.zeros((2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
array_1s = np.ones((2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array_1s = np.ones(4)
array_1s

array([1., 1., 1., 1.])

In [ ]:
# full
array_full = np.full((2,3), fill_value = 10)

In [ ]:
array_full

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
array_full = np.full(shape = (2,3), fill_value = 'aloba')
array_full

array([['aloba', 'aloba', 'aloba'],
       ['aloba', 'aloba', 'aloba']], dtype='<U5')

In [ ]:
import numpy as np
array_full = np.full(7,3)

array_full
#array of length 7 filled with 3

array([3, 3, 3, 3, 3, 3, 3])

In [ ]:
import numpy as np
array_full = np.full((3,5),3)

array_full
#3X5 array filled with 3

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
import numpy as np
array_full = np.full((2,3,5),3)

array_full
#3X5 3D array with two stacks

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [ ]:
import numpy as np
array_full = np.empty(0)

array_full

array([], dtype=float64)

In [ ]:
import numpy as np
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [ ]:
array_empty_like = np.empty_like(matrix_A)
print(array_empty_like.shape)
array_empty_like

(3, 5)


array([[     96815633433624,                   0,     140195097313328,
            140195096437904,     140194383505008],
       [    140194668065776,     140195088917296,     140195096673952,
            140195088917296,     140195088917296],
       [8079523124199318373,                  33,      96792019613008,
            140195103591664,                 208]])

In [ ]:
array_0s_like = np.zeros_like(matrix_A)
print(array_0s_like)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
array_rng = np.arange(6)
array_rng

array([0, 1, 2, 3, 4, 5])

In [ ]:
array_rng = np.arange(2,6,2)
array_rng

array([2, 4])

In [ ]:
array_rng = np.arange(start = 0, stop =  30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [ ]:
# list(range(0,30,2.5))

In [ ]:
array_rng = np.arange(5,30,2.9)
array_rng

array([ 5. ,  7.9, 10.8, 13.7, 16.6, 19.5, 22.4, 25.3, 28.2])

In [ ]:
x = np.array([1, 2, 3, 4, 5])
print(np.mean(x))

3.0


In [ ]:
x = np.array([[1, 2, 20], [4, 5, 6]])
x

array([[ 1,  2, 20],
       [ 4,  5,  6]])

In [ ]:
print(np.mean(x, axis=0))  #column wise

[2.5 3.5 9. ]


In [ ]:
print(np.mean(x, axis=1)) #row wise

[2. 5.]


In [ ]:
print(np.mean(x)) #mean of every value

3.5


In [ ]:
x

array([[ 1,  2, 20],
       [ 4,  5,  6]])

In [ ]:
np.min(x)

1

In [ ]:
np.max(x)

6

In [ ]:
np.amin(x, axis = 0)

array([1, 2, 6])

In [ ]:
x

array([[ 1,  2, 20],
       [ 4,  5,  6]])

In [ ]:
np.minimum.reduce(x)

array([1, 2, 6])

In [ ]:
np.maximum.reduce(x)

array([ 4,  5, 20])

In [ ]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])

In [ ]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [ ]:
np.median(matrix_A)

3.0

In [ ]:
np.median(matrix_A,axis = 1)

array([1., 6., 4.])

In [ ]:
np.mean(matrix_A)

3.4

In [ ]:
np.mean(matrix_A,axis = 1)

array([1. , 5.2, 4. ])

In [ ]:
np.average(matrix_A)

3.4

In [ ]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [ ]:
np.var(matrix_A)

7.84

In [ ]:
np.std(matrix_A)

2.8

In [ ]:

matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A : \n",cov_matrix)

Covariance matrix of matrix_A : 
 [[ 1.5 -2.   2. ]
 [-2.   7.7 -7. ]
 [ 2.  -7.   8.5]]


In [ ]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
corr_matrix = np.corrcoef(matrix_A)
print("Correlation matrix of matrix_A : \n",corr_matrix)

Correlation matrix of matrix_A : 
 [[ 1.         -0.58848989  0.56011203]
 [-0.58848989  1.         -0.8652532 ]
 [ 0.56011203 -0.8652532   1.        ]]


In [ ]:
from math import sqrt
sqrt(-16)

ValueError: math domain error

In [ ]:
a = np.array([1, 2.0, 3, 4, 5])
# set the second element to NaN
# a[1] = np.nan
print(a)


[1. 2. 3. 4. 5.]


In [ ]:
a


array([1., 2., 3., 4., 5.])

In [ ]:
a[a >= 4].size / a.size * 100

40.0

In [ ]:
np.percentile(a,75)

4.0

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
np.mean(a >= 4) * 100

40.0

In [ ]:
txt = "banana"

x = txt.center(100)

print(x)

                                               banana                                               


In [1]:
my_set = {"python", "java", "R"}

In [2]:
my_set.add("scala")    #add "scala" to the set
print(my_set)    #{'scala', 'python', 'java', 'R'}

{'java', 'scala', 'R', 'python'}


In [3]:
my_set.remove("R")    #remove "R" item
print(my_set)    #{'scala', 'python', 'java'}

{'java', 'scala', 'python'}


In [4]:
del my_set