In [ ]:
import numpy as np

array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [ ]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
list_a = [1,2,3]
list_a +[2]


[1, 2, 3, 2]

In [ ]:
list_a = [1,2,3]
list_a +[2,4]

[1, 2, 3, 2, 4]

In [4]:
import numpy as np
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [5]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_b[1]

array([4, 5, 6])

In [ ]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [ ]:
array_b - array_a


array([[-6, -6, -6],
       [-3, -3, -3]])

In [6]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[2,3,3],[9,5,2]])

In [7]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
b

array([[2, 3, 3],
       [9, 5, 2]])

In [9]:
a * b

array([[ 2,  6,  9],
       [27, 20, 10]])