In [ ]:
print(f"hello ALOBA'S")

hello ALOBA'S


In [ ]:
print("Python Print Function")
print("The function is declared like this:")


Python Print Function
The function is declared like this:


In [ ]:
print("hello world ")
print("hello world ")
print("hello world ")

hello world 
hello world 
hello world 


In [ ]:
print("hello world! \nhello world! \nhello world!")

hello world! 
hello world! 
hello world!


In [ ]:
print('Hello' , ' Gomycode.' , 'Today is ' , '4')

Hello  Gomycode. Today is  4


In [ ]:
print('Hello'+'Gomycode')

HelloGomycode


In [ ]:
age = input('Enter your age: ')

Enter your age: True


In [ ]:
print("My age is " + age)

My age is True


In [ ]:
age

7

In [ ]:
type(age)

str

In [ ]:
print("Day 1 - String Manipulation")

Day 1 - String Manipulation


In [ ]:
print("String Concatenation is done with the sign.")


String Concatenation is done with the sign.


In [ ]:
print("Hello world")


Hello world


In [ ]:
print("New lines can be created with a backslash \nand")

New lines can be created with a backslash 
and


In [ ]:
num = 3
if num > 5:
    print(num, "is a positive number.")
    print("This is always printed.")

In [ ]:
rain = 'monday'
if rain == 'sunday':
    print("I won't go to church")
else:
    print("I will go to church")

I will go to church


In [ ]:
age = int(input('Enter your age: '))
if age > 18:
    print('You are allowed')
else:
    print('You are not allowed in')

Enter your age: 4
You are not allowed in


In [ ]:
x=7

if x==1:
      print('X is equal to 1')
elif x==5:
      print('X is equal to 5')
elif x==9.9:
      print('X is equal to 10')
else:
      print('X =', x)

X = 8


In [ ]:
number = input('Enter a number: ')
if type(int(number)) == int:
    print('this is an integer')
elif type(float(number)) == float:
    print('this is a  float')

Enter a number: 9
this is an integer


In [ ]:
type(int(number))

int

In [ ]:
type(9)

int

In [ ]:
gender = input('Enter your gender: ')
age = int(input('Enter your age: '))
if gender == 'M':
    if age > 18:
        print('You can get Jeans of big sizes')
    else:
        print('You cannot get it')
elif gender == 'F':
    print('You are a female')
    if age > 18:
        print('You can get a saloon car')
    elif age == 18:
        print('Wait for one more year')
    else:
        print('You are not allowed to have a saloon car')

Enter your gender: F
Enter your age: 5
You are a female
You are not allowed to have a saloon car


In [ ]:
a = 8
b = 4
c = 7

In [ ]:
(a>b) and (b>c)

False

In [ ]:
False or False

False

In [ ]:
order_total = 150
customer_membership = True

if order_total >= 100 and customer_membership == True:
    print("Discount applied.")
else:
    print("Discount not applied.")

Discount not applied.


In [ ]:
order_total = 75
customer_location = "USA"

if not(order_total >= 50 or customer_location == "USA"):
    print("Free shipping applied.")
else:
    print("Shipping fee applied.")


Shipping fee applied.


In [ ]:
not(False)

True

In [ ]:
not(True)

False

In [ ]:
is_member = False

if not is_member:
    print("Customer is not a member.")
else:
    print("Customer is a member.")

Customer is not a member.


In [ ]:
score = int(input('enter a score'))
if score >= 50 and score <60:
    print('C')
elif score >= 60 and score <70:
    print('B')

enter a score33


In [ ]:
2*2

4

In [ ]:
2**3

8

In [ ]:
8/3

2.6666666666666665

In [ ]:
round(8/3,4)

2.6667

In [ ]:
Result = 8/2
Result /=2
print(Result)

2.0


In [ ]:
num = 3
num = num + 4

In [ ]:
score = 15
print(f"Your score is {score}")

Your score is 15


In [ ]:
print('Your score is' , score)

Your score is 15


In [ ]:
import time, datetime
from datetime import date

In [ ]:
date.today()

datetime.date(2024, 3, 6)

In [ ]:
import math
help(datetime)

Help on module datetime:

NAME
    datetime - Fast implementation of the datetime type.

MODULE REFERENCE
    https://docs.python.org/3.9/library/datetime
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

CLASSES
    builtins.object
        date
            datetime
        time
        timedelta
        tzinfo
            timezone
    
    class date(builtins.object)
     |  date(year, month, day) --> date object
     |  
     |  Methods defined here:
     |  
     |  __add__(self, value, /)
     |      Return self+value.
     |  
     |  __eq__(self, value, /)
     |      Return self==value.
     |  
     |  __format__(...)
     |      Formats self with strftime.
     |  
     |  __ge__(self, value, /)
     |    

In [ ]:
max_age = 90
current_age = int(input('Enter your age'))
remain = max_age-current_age

Enter your age90


In [ ]:
days_left = remain * 365

In [ ]:
weeks_left = remain * 52

In [ ]:
months_left = remain * 12

In [ ]:
print(f"Hello, you have {days_left} days, {weeks_left} weeks, {months_left} months left")

Hello, you have 0 days, 0 weeks, 0 months left


In [ ]:
a = 1 + 2 + 3 + \
    4 + 5 + 6 + \
    7 + 8 + 9

In [ ]:
print(a)

45


In [ ]:
a = 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 +  1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 +  1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 +  1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9

In [ ]:
print(a)

45


In [ ]:
a = (1 + 2 + 3 +
    4 + 5 + 6 -
    7 + 8 + 9)

In [ ]:
print(a)

45


In [ ]:
a = 1; b = 2; c = 3

In [ ]:
print(a,b,c)

1 2 3


In [ ]:
a = 1
b= 2
c= 3

1 2 3


In [ ]:
for i in range(0,3):


0
1
2


In [ ]:
a = 20 #remember that a is the same as apples

In [ ]:
print(a)

20


In [ ]:
#This is a long comment
#and it extends
#to multiple lines

In [ ]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [ ]:
import math

In [ ]:
math.cos(4/5)

0.6967067093471654

In [ ]:
math.pi

3.141592653589793

In [ ]:
round(math.pi,4) #rounds up the decimals

3.1416

In [ ]:
from math import pi
pi

3.141592653589793

In [ ]:
radius = 14
area = math.pi * 14**2

In [ ]:
print(area)

615.7521601035994


In [ ]:
from math import cos

In [ ]:
cos(4/5)

0.6967067093471654

In [ ]:
math.cos(4/5)

In [ ]:
a = 20
apples = 20
numberofapples =20
number_of_apples = 20
number_of_apples_2024 =20
NUMBER_OF_APPLES_2024 =20

In [ ]:
number_of_apples_2024 =20
number_of_apples_2025 =25

In [ ]:
number_of_apples_2024 =20

In [ ]:
name  = 'FaTeemah'

In [ ]:
name.lower()

'fateemah'

In [ ]:
name.upper()

'FATEEMAH'

In [ ]:
name.title()

'Fateemah'

In [ ]:
paragraph = 'Nigeria is a country THAT haS 36 state, for example osun State, OGUN STATE'

In [ ]:
paragraph.title()

'Nigeria Is A Country That Has 36 State, For Example Osun State, Ogun State'

In [ ]:
x = 6
x = 8

In [ ]:
print(x)

8


In [ ]:
x=True
type(x)

bool

In [ ]:
print('hello customer!')
city = input('What city are you from ? ')
pet = input('What is your pet name? ')
print(f'Hello, your brand name is {city+pet}')

hello customer!
What city are you from ? lagos
What is your pet name? rat
Hello, your brand name is lagosrat


In [ ]:
#this code returns the grade of a user when the user gives a score
score = int(input('Enter a score to get a grade:'))
if score >= 70:
    print('You got A')
elif score >= 61 and score <= 69:
    print('You got B')
elif score >= 56 and score <= 60:
    print('You got C')
elif score >= 50 and score <= 55:
    print('You got D')
elif score >= 40 and score <= 49:
    print('You got E')
elif score >= 0 and score <= 39:
    print('You got F')
else:
    print('Invalid number')


Enter a score to get a grade:45
You got B


In [ ]:
score = int(input('Enter a score to get a grade:'))
if score >= 70:
    print('You got A')
elif score >= 61 and score <= 69:
    print('You got B')
elif score >= 56 and score <= 60:
    print('You got C')
elif score >= 50 and score <= 55:
    print('You got D')
elif score >= 40 and score <= 49:
    print('You got E')
elif  0 <= score <= 39:
    print('You got F')
else:
    print('Invalid number')


Enter a score to get a grade:-33
Invalid number


In [ ]:
x = 8
y = 3

In [ ]:
8/3

2.6666666666666665

In [ ]:
x//3

2

In [ ]:
5.34/3

1.78

In [ ]:
5.34//3

1.0

In [ ]:
from math import ceil

In [ ]:
ceil(8/3)

3

In [ ]:
x <= y

False

In [ ]:
students = ['dapo','mobo','lekan','adewunmi','aishat','phabian','murtala','fateemah','aloba']

In [ ]:
x = 12
y = 5
result = x > y

In [ ]:
print(result)

True


In [ ]:
not result

False

False

In [ ]:
not 'lekan'

False

In [ ]:
not(x > y)

False

In [ ]:
x = 'phabian'
y = 'dapo'

In [ ]:
len(x) > len(y)

True

In [ ]:
'b' in 'phabian'

True

In [ ]:
my_string = "Welcome to python"

print(my_string)

Welcome to python


In [ ]:
my_string[0:7:3]

'Wce'

In [ ]:
y = 'aloba'
y[0:4]

'alob'

In [ ]:
str1 = "Welcome to "
str2 ="coding world!"

print("str1 +          str2")

str1 +          str2


In [ ]:
print(str1+               str2)

Welcome to coding world!


In [ ]:
my_string = "Welcome to python"


In [ ]:
len(my_string)

In [ ]:
num = False

In [ ]:
type(num)

bool

In [ ]:
int(5.36)

5

In [ ]:
int(True)

1

In [ ]:
result = float(77)
print(result)

77.0


In [ ]:
result == 77

True

In [ ]:
float('88.8')

88.8

In [ ]:
float('num')

ValueError: could not convert string to float: 'num'

In [ ]:
float(True)

1.0

In [ ]:
1.0 == 1

True

In [ ]:
str(5)

'5'

In [ ]:
my_list = []

In [ ]:
print(my_list)

[]


In [ ]:
len(my_list)

0

In [ ]:
my_list = [1, 2, 3]

In [ ]:
len(my_list)

3

In [ ]:
my_list = [True, "Hello", 3.4]

In [ ]:
my_list = ["python", "java", "SQL", "C++"]

In [ ]:
print(my_list)

['python', 'java', 'SQL', 'C++']


In [ ]:
my_list = ["python", "java", "SQL","R", "SAS", "C++", "php", "html"]

In [ ]:
my_list[6]

'php'

In [ ]:
my_list[:]

['python', 'java', 'SQL', 'R', 'SAS', 'C++', 'php', 'html']

In [ ]:
my_list.append("Matlab")

In [ ]:
print(my_list)

['python', 'java', 'SQL', 'R', 'SAS', 'C++', 'php', 'html', 'Matlab']


In [ ]:
my_list.insert(1,"Spark")

In [ ]:
my_list

['python', 'Spark', 'java', 'SQL', 'R', 'SAS', 'C++', 'php', 'html', 'Matlab']

In [ ]:
my_list[1]="Scala" #replacing method

In [ ]:
my_list

['python', 'Scala', 'java', 'SQL', 'R', 'SAS', 'C++', 'php', 'html', 'Matlab']

In [ ]:
my_list.remove('SQL')

In [ ]:
my_list

['python', 'Scala', 'java', 'R', 'SAS', 'C++', 'php', 'html', 'Matlab']

In [ ]:
del my_list[0]

In [ ]:
my_list

['Scala', 'java', 'R', 'SAS', 'C++', 'php', 'html', 'Matlab']

In [ ]:
my_list[-1] = 'Math'

In [ ]:
my_list

['Scala', 'java', 'R', 'SAS', 'C++', 'php', 'html', 'Math']

In [ ]:
a = ['taiwo','ken','taiwo']

In [ ]:
#to remove the double taiwoz][]
for item in a:
    if 'taiwo' == item:
        a.remove('taiwo')

In [ ]:
a

['ken']

In [ ]:
#start of code
print('Welcome to Python Pizza Deliveries')
size = input('Enter the size you want: \nSmall : S\nMedium : M\nLarge : L\n')
size = size.lower()
add_pepperoni = input('Do you want Pepperoni: Yes or No')
extra_cheese = input('Do you want extra cheese: Yes or No')
bill = 0

#logical part
if size == 's' or size == 'small':
    bill = bill + 15
elif size == 'm' or size == 'medium':
    bill = bill + 20
elif size == 'l' or size == 'large':
    bill = bill + 25
else:
    print('Choose a valid size')

if add_pepperoni == 'Yes' and size == 'S':
    bill = bill + 2
elif add_pepperoni == 'Yes' and size == 'M' or 'L':
    bill = bill + 3
else:
    print('not good')

if extra_cheese == 'Yes':
    bill == bill + 1
    print(f'Your total is ${bill}')
else:
    print(f'Your total is ${bill}')

Welcome to Python Pizza Deliveries


KeyboardInterrupt: Interrupted by user

In [ ]:
#start of code
print('Welcome to Python Pizza Deliveries')
size = input('Enter the size you want: \nSmall : S\nMedium : M\nLarge : L\n')
add_pepperoni = input('Do you want Pepperoni: Yes or No')
extra_cheese = input('Do you want extra cheese: Yes or No')
bill = 0

#logical part
#checking if it is small size
if size == 'S':
    bill = bill + 15
    #checking if it is adding pepperoni
    if add_pepperoni == 'Yes':
        bill = bill + 2
    if extra_cheese == 'Yes':
        bill = bill + 1

elif size == 'M':
    bill = bill + 20
    if add_pepperoni == 'Yes':
        bill = bill + 3
    if extra_cheese == 'Yes':
        bill = bill + 1

elif size == 'L':
    bill = bill + 25
    if add_pepperoni == 'Yes':
        bill = bill + 3
    if extra_cheese == 'Yes':
        bill = bill + 1
else:
    print('Choose a valid size')

print('Your total is ',bill)

In [ ]:
my_list = ['jay','aishat','kemi','alo','daps']

In [ ]:
my_list[:]

['jay', 'aishat', 'kemi', 'alo', 'daps']

In [ ]:
my_list[1] = 'Fateemah'

In [ ]:
my_list

['jay', 'Fateemah', 'kemi', 'alo', 'daps']

In [ ]:
my_list[2:4]

['kemi', 'alo']

In [ ]:
my_dictionary = {"knowledge": "Data Science",
                 6: "python",
                 "year": 2020}

In [ ]:
#item = key:value
#"knowledge": "Data Science"

In [ ]:
my_dictionary

{'knowledge': 'Data Science', 6: 'python', 'year': 2020}

In [ ]:
for content in my_dictionary.keys():     # Loop Through dictionary keys
    print(content)

knowledge
6
year


In [ ]:
for value in my_dictionary.values():    #  Loop Through dictionary values
    print(value)

Data Science
python
2020


In [ ]:
for item in my_dictionary.items():     # Loop Through dictionary items
    print(item)

('knowledge', 'Data Science')
(6, 'python')
('year', 2020)


In [ ]:
len(my_dictionary)

3

In [ ]:
len(my_dictionary)

3

In [ ]:
my_dictionary["year"] = 2024
print(my_dictionary)

{'knowledge': 'Data Science', 6: 'python', 'year': 2024}


In [ ]:
my_dictionary["month"] = 20
print(my_dictionary)

{'knowledge': 'Data Science', 6: 'python', 'year': 2024, 'month': 20}


In [ ]:
my_dictionary[6]

'python'

In [ ]:
my_dictionary.pop("month")

20

In [ ]:
my_set = {"python","A", "java", "R"}

In [ ]:
my_set

{'A', 'R', 'java', 'python'}

In [ ]:
my_set.add("scala")

In [ ]:
my_set.add('java')

In [ ]:
my_set.pop()

'python'

In [ ]:
{1,2,2,2,3,4}

{1, 2, 3, 4}

In [ ]:
my_set.remove("R")

In [ ]:
my_tuple=("python", "java", "R")
print(my_tuple[1])

java


In [ ]:
#cannot work
my_tuple[3] = 'Sql'

TypeError: 'tuple' object does not support item assignment

In [ ]:
int('4')

4

In [ ]:
list1 = ['jay','susan','comfy','asisat','susan']

In [ ]:
type(list1)

list

In [ ]:
#converting from list to tuple
tuple(list1)

('jay', 'susan', 'comfy', 'asisat', 'susan')

In [ ]:
#converting from list to tuple
set(list1)

{'asisat', 'comfy', 'jay', 'susan'}

Randomization

In [ ]:
import random

In [ ]:
random_integer = random.randint(0,100)
print(random_integer)

76


In [ ]:
help(random)

Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.10/library/random.html
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
        bytes
        -----
               uniform bytes (values between 0 and 255)
    
        integers
        --------
               uniform within range
    
        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation
    
        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)


In [ ]:
list1 = ['Bsc','Msc','Phd','Waec','Neco']
random.choice(list1)

'Neco'

In [ ]:
#initializing the seed for reproducibility
random.seed(10000)
random.randrange(3,17,2)

10

14

In [ ]:
random.paretovariate(10)

1.1056637544139685

In [ ]:
Fruits = ['apple','peach','pear']
for item in Fruits :
	print(item)

apple
peach
pear


In [ ]:
students = ['emma','aloba','dapo','mobo','aishat','lekan','adewunmi','phabian','murtala','fateemah']
for student in students:
  print(f'Hi {student}, do you want agbalumo, amala, rice or pizza?')

Hi emma, do you want agbalumo, amala, rice or pizza?
Hi aloba, do you want agbalumo, amala, rice or pizza?
Hi dapo, do you want agbalumo, amala, rice or pizza?
Hi mobo, do you want agbalumo, amala, rice or pizza?
Hi aishat, do you want agbalumo, amala, rice or pizza?
Hi lekan, do you want agbalumo, amala, rice or pizza?
Hi adewunmi, do you want agbalumo, amala, rice or pizza?
Hi phabian, do you want agbalumo, amala, rice or pizza?
Hi murtala, do you want agbalumo, amala, rice or pizza?
Hi fateemah, do you want agbalumo, amala, rice or pizza?


In [ ]:
student_scores = [78, 65, 89, 86, 55, 91, 64, 89]
result = max(student_scores)
for score in student_scores:
  if score < result:
    result = score
print(result)

55


In [ ]:
student_scores = [78, 65, 89, 86, 55, 91, 64, 89]
sorted(student_scores,reverse = True)[0]

91

In [ ]:
max(student_scores)

91

In [ ]:
for i in range(1,11):
	print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(2,23,2):
 print(i)

2
4
6
8
10
12
14
16
18
20
22


In [ ]:
count = 1
while count <=3:
  print(count)
  count = count + 1
  if count == 4:
    print('Try again later')


1
2
3
Try again later


In [ ]:
while True:
  user_input = input("Enter a number (or 'q' to quit):")
  if user_input == 'q':
      break
  else:
      number = int(user_input)
      print("The square of", number, "is", number*number)

Enter a number (or 'q' to quit):7
The square of 7 is 49
Enter a number (or 'q' to quit):q


In [ ]:
count = 2
while count <= 20:
  print(count)
  count = count + 2

2
4
6
8
10
12
14
16
18
20


In [ ]:
initial = 1
max_attempts = 3
correct_bet = 45

print('Welcome to Baba Ijebu')
print('You have only 3 trials for this game')

while initial <= max_attempts:
  guess = int(input('Input a guess: '))
  if guess == correct_bet:
    print('Awesome! You guessed the exact number and you just won a million naira')
  else:
    print('Try again')
  initial = initial + 1

  if max_attempts == initial:
    print('You have exhausted your attempts')


Welcome to Baba Ijebu
You have only 3 trials for this game
Input a guess: 88
Try again
Input a guess: 99
Try again
You have exhausted your attempts
Input a guess: 99
Try again


In [ ]:
initial = 1
max_attempts = 3
correct_bet = 45

print('Welcome to Baba Ijebu')
print('You have only 3 trials for this game')

while initial <= max_attempts: #true
  guess = int(input('Input a guess: '))
  if guess == correct_bet:
    print('Awesome! You guessed the exact number and you just won a million naira')
    break
  else:
      if max_attempts == initial:
        print('You have exhausted your attempts')
      else:
        print('Try again')
        print(f'You have {max_attempts - initial} attempts left')
  initial = initial + 1

Welcome to Baba Ijebu
You have only 3 trials for this game


In [ ]:
while True:
  user_input = input("Enter a number (or 'q' to quit): ")
  if user_input == 'q':
      break
  else:
    number = int(user_input)
    print("The square of", number, "is", number*number)

KeyboardInterrupt: Interrupted by user

In [ ]:
shopping_list = []
while True:
    options = input('Enter an option: You can choose to add, remove or view your cart.\nChoose quit to exit\n')
    if options == 'add':
        item_to_add = input('What do you want to add?: ')
        shopping_list.append(item_to_add)
        emp = {}
        emp[item_to_add] = input('Enter a quantity for your item')
        print('\n')
    elif options == 'remove':
        item_to_remove = input('What do you want to remove?: ')
        shopping_list.remove(item_to_remove)
        print('\n')
    elif options == 'view':
        print('These are the items you added to your cart')
        for item in shopping_list:
            print(item)
        print('\n')
    elif options == 'quit':
        print('Thank you for shopping with us')
        break
    else:
        print('Please put a valid output')
        print('\n')

Enter an option: You can choose to add, remove or view your cart.
Choose quit to exit
add
What do you want to add?: dog
Enter a quantity for your item1


Enter an option: You can choose to add, remove or view your cart.
Choose quit to exit
add
What do you want to add?: rat
Enter a quantity for your item3


Enter an option: You can choose to add, remove or view your cart.
Choose quit to exit
quit
Thank you for shopping with us


In [ ]:
liste = ['Goat','horse','sheep','cattle']
count = 0
for i in liste :
  count +=1
print(count)

4


In [ ]:
liste = ['Goat','horse','sheep','cattle']
len(liste)

4

In [ ]:
st = 5
len(st)

4

In [ ]:
def aishatCodes():
      # set of tasks
     print("Hello Customer, this is aishat codes and you are welcome")
# end of function


In [ ]:
aishatCodes()

Hello Customer, this is aishat codes and you are welcome


In [ ]:
def AlobaEats():
  print('Aloba likes to eat ewa goin, amala and agbalumo every morning and sleep')

In [ ]:
AlobaEats()

Aloba likes to eat ewa goin, amala and agbalumo every morning and sleep


In [ ]:
def my_function(course):
    print(course)
    print('You are welcome')
    print(course, 'is 500k')

In [ ]:
my_function('Data science')

Data science
You are welcome
Data science is 500k


In [ ]:
my_function('Product design')

Product design
You are welcome
Product design is 500k


In [ ]:
my_function('Business INtelligence')

Business INtelligence
You are welcome
Business INtelligence is 500k


In [ ]:
def area(a,b,h):
      print('We are trying to get the area of a trapezium e.g matchbox')
      result = 1/2 * (a + b)*h #area of a trapezium
      print(result )

In [ ]:
area(9,5,2)
area(b=5,h=2,a=9)

We are trying to get the area of a trapezium e.g matchbox
14.0
We are trying to get the area of a trapezium e.g matchbox
14.0


In [ ]:
def my_function(country="Tunisia"):
    print("I am from "+country)

my_function("Maroc")
my_function("Algeria")
my_function()

I am from Maroc
I am from Algeria
I am from Tunisia


In [ ]:
def my_function(name = 'Anonynous'):
    age = input(f'Hi {name}Enter your age:')
    print(f"My name is {name} and my age is {age}")

In [ ]:
my_function('Jacob')

Hi JacobEnter your age:12
My name is Jacob and my age is 12


In [ ]:
my_function('collabo')

Hi AnonynousEnter your age:88
My name is Anonynous and my age is 88


In [ ]:
def minimum(a,b):
    if a<b:
       return(a)
    else:
      return(b)

In [ ]:
result = minimum(110,33)

In [ ]:
print(result)

33


In [ ]:
def Square(length):
  area = length * length
  perimeter = 4 * length

  return area, perimeter

In [ ]:
result1, result2 = Square(1000)

In [ ]:
result1

1000000

In [ ]:
sum = lambda e,b,c,d,a : e*b

In [ ]:
sum(2,6,3,8,6)

12

In [ ]:
year = lambda ch : ch[:4]

In [ ]:
year('2024/18/03')

'2024'

In [ ]:
greeting = lambda name : print(f'Good morning,{name}')

In [ ]:
greeting('Hannah')

Good morning,Hannah


In [ ]:
def greeting(name):
  print(f'Good morning,{name}')

In [ ]:
greeting('Hannah')

Good morning,Hannah


In [ ]:
#map - - - - map(function,iterable)
numbers = [1, 2, 3, 4, 5]
squaring = lambda x: x*x
squared_numbers = map(squaring, numbers)

In [ ]:
#map - - - - map(function,iterable)
squared_numbers = map(lambda x: x*x, [1, 2, 3, 4, 5] )

In [ ]:
list(squared_numbers)

[1, 4, 9, 16, 25]

In [ ]:
list(map(Square, [1,4,6]))

[(1, 4), (16, 16), (36, 24)]

In [ ]:
func = map(lambda x : f'The word is {x}', 'Jayb')

In [ ]:
list(func)

['The word is J', 'The word is a', 'The word is y', 'The word is b']

In [ ]:
func = map(lambda x : f'The word is {x}', input('Enter a name'))

Enter a nameyomi


In [ ]:
list(func)

['The word is y', 'The word is o', 'The word is m', 'The word is i']

In [ ]:
lam_func = lambda x : f'The word is {x}'
name  = 'Jay'
func = map(lam_func, name)
list(func)

['The word is J', 'The word is a', 'The word is y']

In [ ]:
# Write a program that will take a list of temperatures in Celsius and convert them to
# Fahrenheit using the formula: F = (9/5)C + 32
# Hint: you will need to use the map() function and the lambda function to perform the conversion.

In [ ]:
# use this as the list [30,50,90,180,330]

In [ ]:
class Player:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def run(self):
    print(f"{self.name} is running in the game.")
  def tellingAge(self):
    print(f"The age of the player is {self.age}")

In [ ]:
class Player:
  leg = 2 #class attribute

  def __init__(self, name, age):
    self.name = name
    self.age = age
  def run(self):
    print(f"{self.name} is running in the game.")
  def tellingAge(self):
    print(f"The age of the player is {self.age}")

In [ ]:
messi = Player('Messi Lionel',70) #messi is the object. Messi Lionel is the name and 70 is the age
suarez = Player('Suarez',50)

In [ ]:
messi.run(500)

Messi Lionel is running in the game and the distance is 500.


In [ ]:
messi.tellingAge()

The age of the player is 70


In [ ]:
messi.name

'Messi Lionel'

In [ ]:
messi.age

70

In [ ]:
class Player:
    def __init__(self, name, age, language):
        self.name = name
        self.age = age
        self.language = language
    def run(self):
        print(f"{self.name} is running in the game.")

    def speak(self):
        print(f"My name is {self.name} and I am {self.age} years old and the language i speak is {self.language}")

player1 = Player("John", 25,'portuguese')
player1.run() # Output: "John is running in the game."
player1.speak()

John is running in the game.
My name is John and I am 25 years old and the language i speak is portuguese


In [ ]:
class Player:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def run(self):
        print(f"{self.name} is running in the game.")

    def speak(self):
        print(f"My name is {self.name} and I am {self.age} years old")


player1 = Player("John", 25)
player1.run() # Output: "John is running in the game."
player1.speak()

In [ ]:
class Player:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def speak(self):
        print(f"My name is {self.name} and I am {self.age} years old.")

    def run(self):
        # code for running in the game
        print('the player is running')

    def jump(self):
        # code for jumping in the game
        print('the player is jumping')

player1 = Player("John", 25)
player1.speak()

My name is John and I am 25 years old.


In [ ]:
#class child(Parent1, Parent2, Parent3)


class SuperPlayer(Player):
    def __init__(self, name, age):
        super().__init__(name, age)

    def fly(self):
        # code for flying in the game
        print('The player is flying')

super_player = SuperPlayer("Jack", 30)
super_player.speak()
super_player.fly()

My name is Jack and I am 30 years old.
The player is flying


Solution to python questions

Question 1

In [ ]:
fname = input('Enter your name :') #getting input
length_of_name = len(fname) #checking length
#conditional statements
if length_of_name >= 10:
  print('Your name is more than 10 characters')
elif length_of_name > 5 and length_of_name < 10:
  print('Your name is not so long')
elif length_of_name <= 5:
  print('Your name is too short')

Enter your name :Bolarinwa
Your name is not so long


Question 3

In [ ]:
numbers = [43,21,16,13,31,22,53]
sample_no = 0
for num in numbers:
  if num >= sample_no:
    sample_no = num
print(sample_no)

53


Question 4

In [ ]:
numbers = [43,21,16,13,31,22,53]
sample_no = numbers[0]
for num in numbers:
  if num <= sample_no:
    sample_no = num
print(sample_no)

13


Question 5

In [ ]:
54 in range(0,60,2)

True

In [ ]:
even_num = int(input("Enter a number"))
if even_num %2 == 0:
  print("this is an even number")
else:
  print("this is an odd number")

Enter a number1000
this is an even number


In [ ]:
A = ['shola', 'susan', 'bolu','tola','wunmi', 'aishat','fatimah','grace']
B = ['peter','paul','fatimah','wunmi' ,'yomi', 'aishat']
C = []
for name in A:
  if name in B:
    C.append(name)
print(C)

['wunmi', 'aishat', 'fatimah']


In [ ]:
A = ['shola', 'susan', 'bolu','tola','wunmi', 'aishat','fatimah','grace']
B = ['peter','paul','fatimah','wunmi' ,'yomi', 'aishat']
C = []
for name in A:
  for k in B:
    if name == k:
      C.append(name)
print(C)

['wunmi', 'aishat', 'fatimah']


In [ ]:
A = ['shola', 'susan', 'bolu','tola','wunmi', 'aishat','fatimah','grace']
B = ['peter','paul','fatimah','wunmi' ,'yomi', 'aishat']

new_A = set(A)
new_B = set(B)
intersect_result = new_A.intersection(new_B)
print(list(intersect_result))

union_result = new_A.union(new_B)
print(list(union_result))

['wunmi', 'fatimah', 'aishat']
['paul', 'susan', 'tola', 'shola', 'aishat', 'fatimah', 'peter', 'wunmi', 'grace', 'bolu', 'yomi']


In [ ]:
a = [1,4,2,6,2,7,2,8,5,3,4,5,3]
c=[]
d=[]
for i in a:
  if i not in c:
    c.append(i)
  elif i in c:
    d.append(i)

print(c)
print(d)

In [ ]:
a = [1,4,2,6,2,7,2,8,5,3,4,5,3]
c=[]
d=[]
for i in a:
  if i not in c:
    c.append(i)
  elif i in c  and i not in d:
    d.append(i)

print(c)
print(d)

[1, 4, 2, 6, 7, 8, 5, 3]
[2, 4, 5, 3]


In [ ]:
A = ['shola', 'susan', 'bolu','tola','wunmi', 'aishat','fatimah','grace']
for people in A:
  if len(people) >4:
    print(people)

shola
susan
wunmi
aishat
fatimah
grace


In [ ]:
import random
qualification = ['Msc','Bsc','Phd','B.Edu','B.Tech','B.doc']
random.choice(qualification)


'B.Edu'

number 10 - Wunmi

In [ ]:
def search_states(search):
    search = search.lower()
    all_states = ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno",
                     "Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT - Abuja","Gombe",
                     "Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos",
                     "Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"]
    recommended_list = []
    for states in all_states:
        if states.lower().startswith(search):
            recommended_list.append(states)
    return(recommended_list)

In [ ]:
search = input('Enter the letter(s) you want to search:')
result = search_states(search)
print(result)

Enter the letter(s) you want to search:b
['Bauchi', 'Bayelsa', 'Benue', 'Borno']


number 10 - **Jacob**

In [ ]:
def search_states():
    #getting input
    search = input('Enter the letter(s) you want to search:')
    #storing list of states
    all_states = ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno",
                     "Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT - Abuja","Gombe",
                     "Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos",
                     "Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"]
    #creating empty list
    recommended_list = []
    #getting length of input

    search_length = len(search)
    for state in all_states:
        if state[:search_length].lower() == search.lower():
            recommended_list.append(state)

    return recommended_list

In [ ]:
result = search_states()
print('The results are shown below:')
for i in result:
  print(i)

Enter the letter(s) you want to search:o
The results are shown below:


TypeError: 'NoneType' object is not iterable

In [ ]:
students = ['mobo','emma','alo']

In [ ]:
students[3]

IndexError: list index out of range

In [ ]:
print"hello world"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-20-967a5b6875dd>, line 1)

In [ ]:
9 () 2

SyntaxError: invalid syntax (<ipython-input-26-84143fba21fe>, line 1)

In [ ]:
import emma

ModuleNotFoundError: No module named 'emma'

In [ ]:
D1={'1':"aa", '2':"bb", '3':"cc"}
D1['4']

KeyError: '4'

In [ ]:
i=0
while i<4:
  print(i)
  i+=1

In [ ]:
it=iter([1,2,3])

In [ ]:
next(it)

1

In [ ]:
next(it)

2

In [ ]:
next(it)

3

In [ ]:
next(it)

StopIteration: 

In [ ]:
2 + 2

4

In [ ]:
'2' + '21'

'221'

In [ ]:
int('5')

5

In [ ]:
input('Enter a name: ')

KeyboardInterrupt: Interrupted by user

Numpy

In [ ]:
import numpy as np

In [ ]:
a  = np.array(6)

In [ ]:
a.ndim

0

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [4,2,6],[9,23,9]])
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 4,  2,  6],
       [ 9, 23,  9]])

In [ ]:
array_2d.ndim

2

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Print the array
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr.shape

(2, 3)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
arr[1]

array([4, 5, 6])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[1, 0]

4

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [4,6,7]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 7]])

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr[0:3, 0]

array([1, 4, 4])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 6, 7]])

In [ ]:
arr[0:3, 2] #column indexing

array([3, 6, 7])

In [ ]:
arr[2, :] #row indexing

array([4, 6, 7])

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[2,1,2,6],[4,6,8,9],[2,0,5,8],[2,0,9,1],[1,6,2,2]])

In [ ]:
arr

array([[2, 1, 2, 6],
       [4, 6, 8, 9],
       [2, 0, 5, 8],
       [2, 0, 9, 1],
       [1, 6, 2, 2]])

In [ ]:
arr[1:5,1:3]

array([[6, 8],
       [0, 5],
       [0, 9],
       [6, 2]])

In [ ]:
array2 = np.array([1, 2, 3])

In [ ]:
array2

array([1, 2, 3])

In [ ]:
array2[-2]

2

In [ ]:
arr

array([[2, 1, 2, 6],
       [4, 6, 8, 9],
       [2, 0, 5, 8],
       [2, 0, 9, 1],
       [1, 6, 2, 2]])

In [ ]:
arr[3,2] = 44

In [ ]:
arr

array([[ 2,  1,  2,  6],
       [ 4,  6,  8,  9],
       [ 2,  0,  5,  8],
       [ 2,  0, 44,  1],
       [ 1,  6,  2,  2]])

In [ ]:
arr[1,2] = 32

In [ ]:
arr

array([[ 2,  1,  2,  6],
       [ 4,  6, 32,  9],
       [ 2,  0,  5,  8],
       [ 2,  0, 44,  1],
       [ 1,  6,  2,  2]])

In [ ]:
a =np.array([0,0,0,0,1,0,0,0])

In [ ]:
a

array([0, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
a.shape

(8,)

In [ ]:
a.size

8

In [ ]:
a.reshape(1,8)

array([[0, 0, 0, 0, 1, 0, 0, 0]])

In [ ]:
arr

array([[ 2,  1,  2,  6],
       [ 4,  6, 32,  9],
       [ 2,  0,  5,  8],
       [ 2,  0, 44,  1],
       [ 1,  6,  2,  2]])

In [ ]:
arr.shape

(5, 4)

In [ ]:
arr.size

20

In [ ]:
arr.reshape(2,10)

array([[ 2,  1,  2,  6,  4,  6, 32,  9,  2,  0],
       [ 5,  8,  2,  0, 44,  1,  1,  6,  2,  2]])

In [ ]:
array_a = np.array([[1,2,3],
                      [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [ ]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [ ]:
array_a[1,2] = 90
array_a

array([[90,  9,  9],
       [90,  5, 90]])

In [ ]:
array_a[:,0]

array([90, 90])

In [ ]:
array_a

array([[90,  9,  9],
       [90,  5, 90]])

In [ ]:
list_a = [8,7,8]
array_a[0] = list_a
array_a

array([[ 8,  7,  8],
       [90,  5, 90]])

In [ ]:
list_a = [7,8]
array_a[:,0] = list_a
array_a

array([[ 7,  7,  8],
       [ 8,  5, 90]])

In [ ]:
type(array_a[0])

numpy.ndarray

In [ ]:
array_a[:] = 0
array_a

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
array_a = 0
array_a

0

In [ ]:
array_3D = np.array([   [[1,2,3,4,5], [11,21,31,41,51]],

                      [[11,12,13,14,15], [51,52,53,54,5]]

                        ])
array_3D

array([[[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [ ]:
array_3D.shape

(1, 2, 5)

In [ ]:
array_3D[0][1][2]

31

In [ ]:
array_3D[0][0][4]

5

In [ ]:
names = ['susan',['alhaja','dapo','aloba']]

In [ ]:
names[1][1][2]

'p'

In [ ]:
False == False

True

In [ ]:
with open('/content/file_handling.txt') as f:
  print(f.readlines())

['Hello its Monday\n', 'How are you doing\n', 'Hope you are doing fine\n', 'Trust you are great']


In [ ]:
with open('file_handling.txt') as f:
  print(f.readlines())

In [ ]:
with open('newfile.txt', 'w') as n:
  n.write('Today is Tuesday')
  n.write('Its not sunny')


In [ ]:
import pandas as pd

In [ ]:
products = ['A', 'B', 'C', 'D']
products

['A', 'B', 'C', 'D']

In [ ]:
type(products)

list

In [ ]:
new_series = pd.Series(products)
new_series

0    A
1    B
2    C
3    D
dtype: object

In [ ]:
print(type(new_series))

<class 'pandas.core.series.Series'>


In [ ]:
daily_rates_dollars = pd.Series([40, 45, 50, 60])
daily_rates_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [ ]:
import numpy as np
array_a = np.array([10, 20, 30, 40, 50])
array_a

array([10, 20, 30, 40, 50])

In [ ]:
pd.Series(array_a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
color=["pink", "white", "black", "blue"]
occurence = [20, 15, 6, 43]

S=pd.Series(occurence, color )
print(S)

pink     20
white    15
black     6
blue     43
dtype: int64


In [ ]:
color=["pink", "white", "black", "blue"]
S1=pd.Series([20, 15, 6, 43], index=color)
S2=pd.Series([3, 22, 9, 10], index=color)

In [ ]:
S1

pink     20
white    15
black     6
blue     43
dtype: int64

In [ ]:
S2

pink      3
white    22
black     9
blue     10
dtype: int64

In [ ]:
S1 + S2

pink     23
white    37
black    15
blue     53
dtype: int64

In [ ]:
color1=["pink", "white", "black", "blue"]
color2=["cyan", "white", "red", "blue"]

S1=pd.Series([20, 15, 6, 43], index=color1)
S2=pd.Series([3, 22, 9, 10], index=color2)

In [ ]:
S1

pink     20
white    15
black     6
blue     43
dtype: int64

In [ ]:
S2

cyan      3
white    22
red       9
blue     10
dtype: int64

In [ ]:
S1 + S2

black     NaN
blue     53.0
cyan      NaN
pink      NaN
red       NaN
white    37.0
dtype: float64

In [ ]:
data

{'ProductName': ['Product 1', 'Product 2', 'Product 3'],
 'ProductPrice': [10, 20, 30]}

In [ ]:
data = {"ProductName": ["Product 1", "Product 2", "Product 3"], "ProductPrice": [10, 20, 30]}
df1 = pd.DataFrame(data)
df1

ProductName  ProductPrice
0   Product 1            10
1   Product 2            20
2   Product 3            30

In [ ]:
data = {"ProductName": ["Product 1", "Product 2", "Product 3"], "ProductPrice": [10, 20, 30]}
df2 = pd.DataFrame(data, index=['Aa', 'Bb', 'Cc'])
df2

ProductName  ProductPrice
Aa   Product 1            10
Bb   Product 2            20
Cc   Product 3            30

In [ ]:
data = [{"ProductName": "Product 1", "ProductPrice": 10},
        {"ProductName": "Product 2", "ProductPrice": 20},
        {"ProductName": "Product 3", "ProductPrice": 30}]
df3 = pd.DataFrame(data)

In [ ]:
df3

ProductName  ProductPrice
0   Product 1            10
1   Product 2            20
2   Product 3            30

In [ ]:
product_name = pd.Series(["Product 1", "Product 2", "Product 3"])
product_price = pd.Series([10, 20, 30])

data = {"ProductName": product_name, "ProductPrice": product_price}
df4 = pd.DataFrame(data)
df4

ProductName  ProductPrice
0   Product 1            10
1   Product 2            20
2   Product 3            30

In [ ]:
data = [['Product 1', 10], ['Product 2', 20], ['Product 3', 30]]
df5 = pd.DataFrame(data,index = ['a','b','c'], columns = ['ProductName','ProductPrice'])
df5

ProductName  ProductPrice
a   Product 1            10
b   Product 2            20
c   Product 3            30

In [ ]:
data = {'ProductName': ['Product 1', 'Product 2', 'Product 3'], 'ProductPrice': [10, 20, 30]}
ind = ['A', 'B', 'C']
df6 = pd.DataFrame(data, index=ind)
df6

ProductName  ProductPrice
A   Product 1            10
B   Product 2            20
C   Product 3            30